= Quarkus POI

include::./includes/attributes.adoc[]

This extension enables you to use https://poi.apache.org[Apache POI] in your Quarkus application.

https://poi.apache.org[Apache POI] is a Java API for Microsoft Documents. It allows Java programs to read and write files in Microsoft Office formats, such as Word, Excel and PowerPoint. It also allows programs to create new files in these formats. It is an open source project and is available under the Apache License.

== Installation

If you want to use this extension, you need to add the `io.quarkiverse.poi:quarkus-poi` extension first to your build file.

For instance, with Maven, add the following dependency to your POM file:

[source,xml,subs=attributes+]
----
<dependency>
    <groupId>io.quarkiverse.poi</groupId>
    <artifactId>quarkus-poi</artifactId>
    <version>{project-version}</version>
</dependency>
----

== Docker

When building native images in Docker using the standard Quarkus Docker configuration files some additional features need to be
installed to support Apache POI.  Specifically font information is not included in https://developers.redhat.com/products/rhel/ubi[Red Hat's ubi-minimal images].  To install it
simply add these lines to your `DockerFile.native` file:

[source, dockerfile]
----
FROM registry.access.redhat.com/ubi9/ubi-minimal:9.5

######################### Set up environment for POI #############################
RUN microdnf update -y && microdnf install -y freetype fontconfig && microdnf clean all
######################### Set up environment for POI #############################

WORKDIR /work/
RUN chown 1001 /work \
    && chmod "g+rwX" /work \
    && chown 1001:root /work
# Shared objects to be dynamically loaded at runtime as needed,
COPY --chown=1001:root --chmod=0755 target/*.properties target/*.so /work/
COPY --chown=1001:root --chmod=0755 target/*-runner /work/application
# Permissions fix for Windows
RUN chmod "ugo+x" /work/application
EXPOSE 8080
USER 1001

CMD ["./application", "-Dquarkus.http.host=0.0.0.0"]
----

CAUTION: Make sure `.dockerignore` does not exclude `.so` files!

